# Generated by Django 3.1 on 2021-04-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restorantApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restmenumodel',
            name='restorant',
        ),
        migrations.RemoveField(
            model_name='restorantmodel',
            name='rest_dislike',
        ),
        migrations.RemoveField(
            model_name='restorantmodel',
            name='rest_like',
        ),
        migrations.RemoveField(
            model_name='restorantmodel',
            name='root_usr',
        ),
        migrations.DeleteModel(
            name='restFoodModel',
        ),
        migrations.DeleteModel(
            name='restMenuModel',
        ),
        migrations.DeleteModel(
            name='restorantModel',
        ),
    ]
