# Generated by Django 3.1 on 2021-04-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restorantApp', '0003_restfoodmodel_restmenumodel_restorantmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='restorantmodel',
            name='rest_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
